### ISSUE TITLE
Overlapping partial Nyans

### ISSUE THREAD

**Issue by mathieumg** [alexkuz/nyan-progress-webpack-plugin#1]
![screenshot from 2015-09-09 13 09 39](https://cloud.githubusercontent.com/assets/1624812/9768790/f61709b2-56f3-11e5-839d-e7a34be9fbcd.png)

As you can see, there seems to exist a condition where multiple fast initial messages creates multiple partial Nyans before the one that ends up working/tracking the whole progress.

I'm on v1.0.3 and my dev server config is:

```js
devServer: {
  quiet: false,
  noInfo: false,
  stats: {
    assets: false,
    colors: true,
    version: false,
    hash: false,
    timings: false,
    chunks: false,
    chunkModules: false
  }
},
```

**Comment by alexkuz** [comment]
Yeah, that's because you have some console output occurred during progress (that "Child" line, I believe). I don't know is there a way to track what was printed in console from outside the plugin (probably there's no way).


Actually, I just checked ASCII escape codes - there is a "Save/restore cursor position" command, which could help (they say it's not widely supported by terminals though).

Another way to solve it (kinda) is to print nyan cat with a left offset, so that it's not overlapping other messages.

**Comment by alexkuz** [comment]
@mathieumg btw what terminal and font are you using? Your cat looks more like Cheshire cat :)

**Comment by alexkuz** [comment]
@mathieumg check out a new version, should be fixed now.

**Comment by mathieumg** [comment]
Actually that made it worse. :( 

![screenshot from 2015-09-09 22 36 11](https://cloud.githubusercontent.com/assets/1624812/9778928/8dcda87e-5744-11e5-9af2-ce743ceb155e.png)

![screenshot from 2015-09-09 22 37 01](https://cloud.githubusercontent.com/assets/1624812/9778927/8dc64f7a-5744-11e5-8bc6-bd4217403de9.png)

I wish I could screencap it, the behaviour is pretty spectacular on 1.1 haha. :stuck_out_tongue: 

Do you want me to setup a toy project to reproduce the issue?

I'm using Ubuntu Mono and Bash on my home PC (the screenshots so far), I'll try with whatever I have at work tomorrow.

Thanks for the quick reaction by the way!

**Comment by alexkuz** [comment]
@mathieumg try to turn off `webpack.ProgressPlugin` if you have it, they are not supposed to be used together (should mention it in README probably).

**Comment by mathieumg** [comment]
I have the same behavior (Nyan scrolling down and leaving trails) even without `--progress`. I also still get the two initial partial Nyans (screenshot in OP), but on 1.0 the progress + Nyan were working correctly after that.

**Comment by alexkuz** [comment]
Hmm. Can you make an example project then?

**Comment by mathieumg** [comment]
Yeah, I'll try to do that!

**Comment by alexkuz** [comment]
@mathieumg just reproduced the issue - it happens when console output doesn't fit screen height. Will try to fix that.

**Comment by mathieumg** [comment]
Cool! Sorry for being slow on this, I've been held up with school as of late. :x

**Comment by alexkuz** [comment]
Should be better now

**Comment by alexkuz** [comment]
@mathieumg can you check it, so I can close this issue?

**Comment by mathieumg** [comment]
I think I had and there were still issues, but I wanted to revalidate. I'll try to recheck that ASAP.

**Comment by alexkuz** [comment]
Turned out I forgot that I'm using non-standard terminal :) Seems like default terminal in MacOS doesn't support restoring/saving cursor position, so I had to disable that feature by default.
